import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { moveModInText, parseModlist, setEnabledInText } from './modlistText';
import type { Mod, Separator } from '../model';

const fixtureDir = join(__dirname, '..', 'test', 'fixtures', 'mo2-instance');
const defaultModlist = () =>
  readFileSync(join(fixtureDir, 'profiles', 'Default', 'modlist.txt'), 'utf8');

describe('setEnabledInText — byte-faithful surgical edit', () => {
  it('flips exactly one prefix and leaves every other byte (CRLF, comment, * lines) identical', () => {
    const input = defaultModlist();
    const out = setEnabledInText(input, 'SKK Fast Start new game (Fallout 4)', false);

    // Only difference: the one line's leading + becomes -
    expect(out).toBe(input.replace('+SKK Fast Start new game (Fallout 4)', '-SKK Fast Start new game (Fallout 4)'));
    expect(out.length).toBe(input.length); // same byte length
    expect(out).toContain('\r\n'); // CRLF preserved
    expect(out).toContain('# This file was automatically generated by Mod Organizer.\r\n'); // comment untouched
    expect(out).toContain('*DLC: Automatron\r\n'); // unmanaged line untouched
  });

  it('is a no-op when the mod already has the requested state', () => {
    const input = defaultModlist();
    expect(setEnabledInText(input, 'SKK Fast Start new game (Fallout 4)', true)).toBe(input);
  });

  it('round-trips: disable then re-enable yields the original bytes', () => {
    const input = defaultModlist();
    const disabled = setEnabledInText(input, 'SKK Fast Start new game (Fallout 4)', false);
    expect(setEnabledInText(disabled, 'SKK Fast Start new game (Fallout 4)', true)).toBe(input);
  });

  it('throws when the mod name is not present', () => {
    expect(() => setEnabledInText(defaultModlist(), 'No Such Mod', false)).toThrow(/No Such Mod/);
  });

  it('does not match a separator line as a mod', () => {
    // "Unassigned (Modlist Development)" exists only as a separator; toggling it as a mod must fail
    expect(() => setEnabledInText(defaultModlist(), 'Unassigned (Modlist Development)', false)).toThrow();
  });
});

describe('moveModInText — byte-faithful reorder by entry index', () => {
  const names = (text: string) => parseModlist(text).map((e) => e.name);

  it('moves a mod to the top (entry index 0), preserving the comment header and all bytes', () => {
    const out = moveModInText(defaultModlist(), 'Cracked and Smudged Pip-Boy Screen', 0);
    expect(names(out)).toEqual([
      'Cracked and Smudged Pip-Boy Screen',
      'SKK Fast Start new game (Fallout 4)',
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
    ]);
    // header still first, * lines still last, CRLF intact, no bytes added/lost
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
    expect(out.length).toBe(defaultModlist().length);
  });

  it('moves a mod down to a later entry index', () => {
    const out = moveModInText(defaultModlist(), 'SKK Fast Start new game (Fallout 4)', 2);
    expect(names(out)).toEqual([
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'SKK Fast Start new game (Fallout 4)',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
  });

  it('clamps an out-of-range index to the last entry position', () => {
    const out = moveModInText(defaultModlist(), 'SKK Fast Start new game (Fallout 4)', 99);
    expect(names(out).at(-1)).toBe('SKK Fast Start new game (Fallout 4)');
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true); // * block still trails
  });

  it('throws when the mod is absent', () => {
    expect(() => moveModInText(defaultModlist(), 'No Such Mod', 0)).toThrow(/No Such Mod/);
  });
});

describe('parseModlist', () => {
  it('surfaces mods and separators in priority order, ignoring comment/* /blank lines', () => {
    const entries = parseModlist(defaultModlist());
    expect(entries).toEqual([
      { kind: 'mod', name: 'SKK Fast Start new game (Fallout 4)', enabled: true },
      { kind: 'separator', name: 'Unassigned (Modlist Development)', enabled: false },
      { kind: 'mod', name: '[NODELETE] Radfall', enabled: true },
      { kind: 'mod', name: 'Unofficial Fallout 4 Patch', enabled: true },
      { kind: 'separator', name: 'Radfall - All-In-One Survival Overhaul', enabled: false },
      { kind: 'mod', name: 'ENBoost - 12k', enabled: true },
      { kind: 'mod', name: 'Harder VATS', enabled: false },
      { kind: 'mod', name: 'Cracked and Smudged Pip-Boy Screen', enabled: true },
    ] satisfies (Mod | Separator)[]);
  });

  it('recognizes an enabled separator (+…_separator)', () => {
    const entries = parseModlist('+ENB_separator\r\n');
    expect(entries).toEqual([{ kind: 'separator', name: 'ENB', enabled: true }]);
  });

  it('returns no entries for a file of only comment/* /blank lines', () => {
    expect(parseModlist('# header\r\n*DLC: Automatron\r\n\r\n')).toEqual([]);
  });
});

// Opt-in at-scale backstop: byte-faithful round-trip against the real full LitR
// modlist.txt. Skipped when the install is absent (CI, Windows, other machines).
const litrInstance = process.env.MEDIT_LITR_INSTANCE ?? join(homedir(), 'Games', 'FO4', 'LitR');
const litrModlist = join(litrInstance, 'profiles', 'Life in the Ruins', 'modlist.txt');
const hasLitr = existsSync(litrModlist);

describe.skipIf(!hasLitr)('full LitR round-trip (opt-in)', () => {
  it('toggling a real mod off then on reproduces the original bytes exactly', () => {
    const input = readFileSync(litrModlist, 'utf8');
    const mod = 'SKK Fast Start new game (Fallout 4)';
    const disabled = setEnabledInText(input, mod, false);
    expect(disabled).not.toBe(input);
    expect(setEnabledInText(disabled, mod, true)).toBe(input);
  });
});
