import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import {
  deleteSeparatorInText,
  insertSeparatorAtIndexInText,
  moveModInText,
  moveModToSeparatorEndInText,
  moveSeparatorBlockInText,
  parseModlist,
  removeModFromText,
  renameSeparatorInText,
  setEnabledInText,
} from './modlistText';
import type { Mod, Separator } from '../model';

const fixtureDir = join(__dirname, '..', 'test', 'fixtures', 'mo2-instance');
const defaultModlist = () =>
  readFileSync(join(fixtureDir, 'profiles', 'Default', 'modlist.txt'), 'utf8');

describe('setEnabledInText — byte-faithful surgical edit', () => {
  it('flips exactly one prefix and leaves every other byte (CRLF, comment, * lines) identical', () => {
    const input = defaultModlist();
    const out = setEnabledInText(input, 'SKK Fast Start new game (Fallout 4)', false);

    // Only difference: the one line's leading + becomes -
    expect(out).toBe(input.replace('+SKK Fast Start new game (Fallout 4)', '-SKK Fast Start new game (Fallout 4)'));
    expect(out.length).toBe(input.length); // same byte length
    expect(out).toContain('\r\n'); // CRLF preserved
    expect(out).toContain('# This file was automatically generated by Mod Organizer.\r\n'); // comment untouched
    expect(out).toContain('*DLC: Automatron\r\n'); // unmanaged line untouched
  });

  it('is a no-op when the mod already has the requested state', () => {
    const input = defaultModlist();
    expect(setEnabledInText(input, 'SKK Fast Start new game (Fallout 4)', true)).toBe(input);
  });

  it('round-trips: disable then re-enable yields the original bytes', () => {
    const input = defaultModlist();
    const disabled = setEnabledInText(input, 'SKK Fast Start new game (Fallout 4)', false);
    expect(setEnabledInText(disabled, 'SKK Fast Start new game (Fallout 4)', true)).toBe(input);
  });

  it('throws when the mod name is not present', () => {
    expect(() => setEnabledInText(defaultModlist(), 'No Such Mod', false)).toThrow(/No Such Mod/);
  });

  it('does not match a separator line as a mod', () => {
    // "Unassigned (Modlist Development)" exists only as a separator; toggling it as a mod must fail
    expect(() => setEnabledInText(defaultModlist(), 'Unassigned (Modlist Development)', false)).toThrow();
  });
});

describe('moveModInText — byte-faithful reorder by entry index', () => {
  const names = (text: string) => parseModlist(text).map((e) => e.name);

  it('moves a mod to the top (entry index 0), preserving the comment header and all bytes', () => {
    const out = moveModInText(defaultModlist(), 'Cracked and Smudged Pip-Boy Screen', 0);
    expect(names(out)).toEqual([
      'Cracked and Smudged Pip-Boy Screen',
      'SKK Fast Start new game (Fallout 4)',
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
    ]);
    // header still first, * lines still last, CRLF intact, no bytes added/lost
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
    expect(out.length).toBe(defaultModlist().length);
  });

  it('moves a mod down to a later entry index', () => {
    const out = moveModInText(defaultModlist(), 'SKK Fast Start new game (Fallout 4)', 2);
    expect(names(out)).toEqual([
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'SKK Fast Start new game (Fallout 4)',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
  });

  it('clamps an out-of-range index to the last entry position', () => {
    const out = moveModInText(defaultModlist(), 'SKK Fast Start new game (Fallout 4)', 99);
    expect(names(out).at(-1)).toBe('SKK Fast Start new game (Fallout 4)');
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true); // * block still trails
  });

  it('throws when the mod is absent', () => {
    expect(() => moveModInText(defaultModlist(), 'No Such Mod', 0)).toThrow(/No Such Mod/);
  });
});

describe('parseModlist', () => {
  it('surfaces mods and separators in priority order, ignoring comment/* /blank lines', () => {
    const entries = parseModlist(defaultModlist());
    expect(entries).toEqual([
      { kind: 'mod', name: 'SKK Fast Start new game (Fallout 4)', enabled: true },
      { kind: 'separator', name: 'Unassigned (Modlist Development)', enabled: false },
      { kind: 'mod', name: '[NODELETE] Radfall', enabled: true },
      { kind: 'mod', name: 'Unofficial Fallout 4 Patch', enabled: true },
      { kind: 'separator', name: 'Radfall - All-In-One Survival Overhaul', enabled: false },
      { kind: 'mod', name: 'ENBoost - 12k', enabled: true },
      { kind: 'mod', name: 'Harder VATS', enabled: false },
      { kind: 'mod', name: 'Cracked and Smudged Pip-Boy Screen', enabled: true },
    ] satisfies (Mod | Separator)[]);
  });

  it('recognizes an enabled separator (+…_separator)', () => {
    const entries = parseModlist('+ENB_separator\r\n');
    expect(entries).toEqual([{ kind: 'separator', name: 'ENB', enabled: true }]);
  });

  it('returns no entries for a file of only comment/* /blank lines', () => {
    expect(parseModlist('# header\r\n*DLC: Automatron\r\n\r\n')).toEqual([]);
  });
});

// Fixture entries (0-based):
// 0  mod  SKK Fast Start new game (Fallout 4)  [+]
// 1  sep  Unassigned (Modlist Development)      [-]
// 2  mod  [NODELETE] Radfall                    [+]
// 3  mod  Unofficial Fallout 4 Patch            [+]
// 4  sep  Radfall - All-In-One Survival Overhaul [-]
// 5  mod  ENBoost - 12k                         [+]
// 6  mod  Harder VATS                           [-]
// 7  mod  Cracked and Smudged Pip-Boy Screen    [+]

const names = (text: string) => parseModlist(text).map((e) => e.name);

describe('insertSeparatorAtIndexInText', () => {
  it('inserts after the given entry index, preserving comment header, CRLF, and * lines', () => {
    const out = insertSeparatorAtIndexInText(defaultModlist(), 'New Sep', 0);
    expect(names(out)).toEqual([
      'SKK Fast Start new game (Fallout 4)',
      'New Sep',
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
    expect(out).toContain('+New Sep_separator\r\n');
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
  });

  it('inserts after the last entry when afterIndex is at the end', () => {
    const out = insertSeparatorAtIndexInText(defaultModlist(), 'Tail Sep', 7);
    expect(names(out).at(-1)).toBe('Tail Sep');
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
  });

  it('clamps an out-of-range afterIndex to the last entry', () => {
    const out = insertSeparatorAtIndexInText(defaultModlist(), 'End Sep', 999);
    expect(names(out).at(-1)).toBe('End Sep');
  });

  it('new separator entry is parsed as a separator, not a mod', () => {
    const out = insertSeparatorAtIndexInText(defaultModlist(), 'My Group', 3);
    const entry = parseModlist(out).find((e) => e.name === 'My Group');
    expect(entry?.kind).toBe('separator');
  });
});

describe('renameSeparatorInText', () => {
  it('replaces only the separator name, preserving prefix, suffix, CRLF, and all other bytes', () => {
    const out = renameSeparatorInText(
      defaultModlist(),
      'Unassigned (Modlist Development)',
      'Core Mods',
    );
    expect(names(out)).toEqual([
      'SKK Fast Start new game (Fallout 4)',
      'Core Mods',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
    expect(out).toContain('-Core Mods_separator\r\n');
    expect(out).not.toContain('Unassigned');
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
  });

  it('throws when the separator is not present', () => {
    expect(() => renameSeparatorInText(defaultModlist(), 'No Such Sep', 'X')).toThrow(/No Such Sep/);
  });
});

describe('deleteSeparatorInText', () => {
  it('removes only the separator line; child mods remain, promoted to ungrouped or prior separator', () => {
    const out = deleteSeparatorInText(defaultModlist(), 'Unassigned (Modlist Development)');
    expect(names(out)).toEqual([
      'SKK Fast Start new game (Fallout 4)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
    expect(out).not.toContain('Unassigned');
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
  });

  it('throws when the separator is not present', () => {
    expect(() => deleteSeparatorInText(defaultModlist(), 'No Such Sep')).toThrow(/No Such Sep/);
  });
});

describe('removeModFromText', () => {
  it('removes the mod entry line entirely, leaving all other bytes intact', () => {
    const out = removeModFromText(defaultModlist(), '[NODELETE] Radfall');
    expect(names(out)).toEqual([
      'SKK Fast Start new game (Fallout 4)',
      'Unassigned (Modlist Development)',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
    expect(out).not.toContain('[NODELETE] Radfall');
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
  });

  it('throws when the mod is absent', () => {
    expect(() => removeModFromText(defaultModlist(), 'No Such Mod')).toThrow(/No Such Mod/);
  });

  it('does not remove a separator line when given only the separator base name', () => {
    expect(() =>
      removeModFromText(defaultModlist(), 'Unassigned (Modlist Development)'),
    ).toThrow();
  });
});

describe('moveModToSeparatorEndInText', () => {
  it('moves a mod to the end of a target separator section', () => {
    // Move SKK (ungrouped) into Radfall separator, which has ENBoost/HarderVATS/Cracked
    const out = moveModToSeparatorEndInText(
      defaultModlist(),
      'SKK Fast Start new game (Fallout 4)',
      'Radfall - All-In-One Survival Overhaul',
    );
    expect(names(out)).toEqual([
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
      'SKK Fast Start new game (Fallout 4)',
    ]);
  });

  it('moves a mod to the ungrouped section (before first separator) when separatorName is null', () => {
    // [NODELETE] is under Unassigned; move it to ungrouped (after SKK, before Unassigned)
    const out = moveModToSeparatorEndInText(defaultModlist(), '[NODELETE] Radfall', null);
    expect(names(out)).toEqual([
      'SKK Fast Start new game (Fallout 4)',
      '[NODELETE] Radfall',
      'Unassigned (Modlist Development)',
      'Unofficial Fallout 4 Patch',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
  });

  it('appends to separator with no children (separator immediately followed by next separator)', () => {
    const text = '# h\r\n+A\r\n+Sep1_separator\r\n+Sep2_separator\r\n+B\r\n';
    const out = moveModToSeparatorEndInText(text, 'A', 'Sep1');
    expect(names(out)).toEqual(['Sep1', 'A', 'Sep2', 'B']);
  });

  it('throws when the mod is absent', () => {
    expect(() =>
      moveModToSeparatorEndInText(defaultModlist(), 'No Such Mod', null),
    ).toThrow(/No Such Mod/);
  });

  it('throws when the separator is absent', () => {
    expect(() =>
      moveModToSeparatorEndInText(defaultModlist(), 'ENBoost - 12k', 'No Such Sep'),
    ).toThrow(/No Such Sep/);
  });
});

describe('moveSeparatorBlockInText', () => {
  it('moves a separator and all its children as a block to a new position', () => {
    // Move Unassigned block (sep + [NODELETE] + Unofficial) to toIndex=5 (end, after Cracked)
    // After removing block: SKK(0), Radfall sep(1), ENBoost(2), HarderVATS(3), Cracked(4)
    // clamped=5 ≥ length(5) → insert after last entry (after Cracked)
    const out = moveSeparatorBlockInText(
      defaultModlist(),
      'Unassigned (Modlist Development)',
      5,
    );
    expect(names(out)).toEqual([
      'SKK Fast Start new game (Fallout 4)',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
    ]);
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
  });

  it('moves a separator block to the front (toIndex=0)', () => {
    // After removing Unassigned block: SKK(0), Radfall sep(1), ...
    // toIndex=0: insert before SKK
    const out = moveSeparatorBlockInText(
      defaultModlist(),
      'Unassigned (Modlist Development)',
      0,
    );
    expect(names(out)).toEqual([
      'Unassigned (Modlist Development)',
      '[NODELETE] Radfall',
      'Unofficial Fallout 4 Patch',
      'SKK Fast Start new game (Fallout 4)',
      'Radfall - All-In-One Survival Overhaul',
      'ENBoost - 12k',
      'Harder VATS',
      'Cracked and Smudged Pip-Boy Screen',
    ]);
  });

  it('preserves every non-entry byte (CRLF, comment header, * lines)', () => {
    const out = moveSeparatorBlockInText(defaultModlist(), 'Unassigned (Modlist Development)', 5);
    expect(out.startsWith('# This file was automatically generated by Mod Organizer.\r\n')).toBe(true);
    expect(out.endsWith('*Unmanaged: ccSBJFO4003-Grenade\r\n')).toBe(true);
    expect(out).toContain('\r\n');
  });

  it('throws when the separator is absent', () => {
    expect(() =>
      moveSeparatorBlockInText(defaultModlist(), 'No Such Sep', 0),
    ).toThrow(/No Such Sep/);
  });
});

// Opt-in at-scale backstop: byte-faithful round-trip against the real full LitR
// modlist.txt. Skipped when the install is absent (CI, Windows, other machines).
const litrInstance = process.env.MEDIT_LITR_INSTANCE ?? join(homedir(), 'Games', 'FO4', 'LitR');
const litrModlist = join(litrInstance, 'profiles', 'Life in the Ruins', 'modlist.txt');
const hasLitr = existsSync(litrModlist);

describe.skipIf(!hasLitr)('full LitR round-trip (opt-in)', () => {
  it('toggling a real mod off then on reproduces the original bytes exactly', () => {
    const input = readFileSync(litrModlist, 'utf8');
    const mod = 'SKK Fast Start new game (Fallout 4)';
    const disabled = setEnabledInText(input, mod, false);
    expect(disabled).not.toBe(input);
    expect(setEnabledInText(disabled, mod, true)).toBe(input);
  });
});
